spring.datasource.url=jdbc:mysql://localhost:3306/smartcampus
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.google.client-id=231343473626-vlq9l3a7qs5gk9knttrs9133nb48a6b1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=profile,email

server.port=8081




